// Single source of truth for the multi-sheet product-import workbook.
// Both the parser (productImport.service.js) and the template generator
// (productImportTemplate.service.js) read from this so columns never drift.
//
// column.type is a parsing/validation hint:
//   "string" | "number" | "url" | "urlList" | "csvList" | "pipeList" | "date" | "enum"
//
// For Products columns, `dropdown` describes the data-validation source:
//   { sheet: "Categories", column: 1 }  -> live cross-sheet list
//   { values: [...] }                   -> fixed inline list
//   { list: "colors" | "tags" | "subcategories" } -> column on the hidden Lists sheet

const SHEET = {
  CATEGORIES: "Categories",
  BRANDS: "Brands",
  PRODUCT_TYPES: "ProductTypes",
  PRODUCTS: "Products",
};

const STATUS_VALUES = ["in-stock", "out-of-stock", "discontinued"];
const CATEGORY_STATUS_VALUES = ["Show", "Hide"];
const BRAND_STATUS_VALUES = ["active", "inactive"];

// Fixed colour palette. The user picks a name in Excel; the backend stores
// both the name and the matching hex code on the product.
const COLOR_OPTIONS = [
  { name: "Black", code: "#000000" },
  { name: "White", code: "#FFFFFF" },
  { name: "Silver", code: "#C0C0C0" },
  { name: "Grey", code: "#808080" },
  { name: "Stainless Steel", code: "#CAD0D4" },
  { name: "Red", code: "#E53935" },
  { name: "Blue", code: "#1E88E5" },
  { name: "Green", code: "#2E7D32" },
  { name: "Beige", code: "#F5F5DC" },
  { name: "Gold", code: "#D4AF37" },
  { name: "Brown", code: "#795548" },
  { name: "Rose Gold", code: "#B76E79" },
];

// Suggested tag palette for home-appliance / electronics products.
const TAG_OPTIONS = [
  "Best Seller",
  "New Arrival",
  "Sale",
  "Energy Efficient",
  "Smart Home",
  "Wireless",
  "Portable",
  "Kitchen",
  "Laundry",
  "Cooling",
  "Heating",
  "Cleaning",
  "Refrigerator",
  "Washing Machine",
  "Microwave",
  "Oven",
  "Air Conditioner",
  "Vacuum Cleaner",
  "Television",
  "Audio",
  "Computers",
  "Mobile",
  "Gaming",
  "Accessories",
];

// ---------- Categories sheet ----------
const CATEGORY_COLUMNS = [
  {
    key: "category_name",
    header: "category_name",
    required: true,
    type: "string",
    width: 26,
    example: "Headphones",
    note: "Category name (stored as 'parent'). Must be unique.",
  },
  {
    key: "productType",
    header: "productType",
    required: true,
    type: "string",
    width: 18,
    example: "electronics",
    note: "Pick from the dropdown (sourced from the ProductTypes sheet).",
    dropdown: { sheet: SHEET.PRODUCT_TYPES, column: 1 },
  },
  {
    key: "subcategories",
    header: "subcategories",
    required: false,
    type: "pipeList",
    width: 45,
    example: "Bluetooth Headphones | On-Ear Headphones | Kids Headphones",
    note: "Sub-categories (children), separated by | (pipe).",
  },
  {
    key: "image",
    header: "image",
    required: false,
    type: "url",
    width: 45,
    example: "https://res.cloudinary.com/demo/image/upload/v1/cat/headphones.png",
    note: "Optional. Full Cloudinary URL for the category image.",
  },
  {
    key: "description",
    header: "description",
    required: false,
    type: "string",
    width: 40,
    example: "All headphones and accessories.",
    note: "Optional.",
  },
  {
    key: "status",
    header: "status",
    required: false,
    type: "enum",
    width: 12,
    example: "Show",
    note: "Show or Hide. Defaults to Show.",
    dropdown: { values: CATEGORY_STATUS_VALUES },
  },
];

// ---------- Brands sheet ----------
const BRAND_COLUMNS = [
  {
    key: "name",
    header: "name",
    required: true,
    type: "string",
    width: 22,
    example: "Logitech",
    note: "Brand name. Must be unique.",
  },
  {
    key: "logo",
    header: "logo",
    required: false,
    type: "url",
    width: 45,
    example: "https://res.cloudinary.com/demo/image/upload/v1/brand/logitech.png",
    note: "Optional. If provided, must be a full URL.",
  },
  {
    key: "description",
    header: "description",
    required: false,
    type: "string",
    width: 40,
    example: "Computer peripherals manufacturer.",
    note: "Optional.",
  },
  {
    key: "email",
    header: "email",
    required: false,
    type: "string",
    width: 24,
    example: "support@logitech.com",
    note: "Optional.",
  },
  {
    key: "website",
    header: "website",
    required: false,
    type: "string",
    width: 24,
    example: "logitech.com",
    note: "Optional.",
  },
  {
    key: "location",
    header: "location",
    required: false,
    type: "string",
    width: 22,
    example: "Lausanne, Switzerland",
    note: "Optional.",
  },
  {
    key: "status",
    header: "status",
    required: false,
    type: "enum",
    width: 12,
    example: "active",
    note: "active or inactive. Defaults to active.",
    dropdown: { values: BRAND_STATUS_VALUES },
  },
];

// ---------- ProductTypes sheet ----------
const PRODUCT_TYPE_COLUMNS = [
  {
    key: "name",
    header: "name",
    required: true,
    type: "string",
    width: 24,
    example: "electronics",
    note: "Product type name (3-200 characters). Must be unique.",
  },
  {
    key: "image",
    header: "image",
    required: false,
    type: "url",
    width: 45,
    example: "https://res.cloudinary.com/demo/image/upload/v1/type/electronics.png",
    note: "Optional. Full Cloudinary URL.",
  },
];

// ---------- Products sheet ----------
const PRODUCT_COLUMNS = [
  {
    key: "title",
    header: "title",
    required: true,
    type: "string",
    width: 30,
    example: "Wireless Headphones Pro",
    note: "Product name. The slug is generated from this automatically.",
  },
  {
    key: "sku",
    header: "sku",
    required: true,
    type: "string",
    width: 16,
    example: "WH-PRO-001",
    note: "Unique. Rows with a SKU duplicated in the file or already in the database are skipped and reported.",
  },
  {
    key: "price",
    header: "price",
    required: true,
    type: "number",
    width: 10,
    example: 120,
    note: "Number >= 0.",
  },
  {
    key: "quantity",
    header: "quantity",
    required: true,
    type: "number",
    width: 10,
    example: 50,
    note: "Number >= 0. Sets status automatically when status is blank.",
  },
  {
    key: "color_name",
    header: "color_name",
    required: true,
    type: "string",
    width: 18,
    example: "Black",
    note: "Pick a colour from the dropdown. The matching hex code is filled in automatically.",
    dropdown: { list: "colors" },
  },
  {
    key: "image",
    header: "image",
    required: false,
    type: "url",
    width: 45,
    example: "https://res.cloudinary.com/demo/image/upload/v1/products/main.jpg",
    note: "Optional. Main image as a full Cloudinary URL. If left blank, a placeholder is used and you can upload the real image later on the product's edit page.",
  },
  {
    key: "category_name",
    header: "category_name",
    required: true,
    type: "string",
    width: 22,
    example: "Headphones",
    note: "Pick from the dropdown (sourced from the Categories sheet).",
    dropdown: { sheet: SHEET.CATEGORIES, column: 1 },
  },
  {
    key: "subcategory",
    header: "subcategory",
    required: false,
    type: "string",
    width: 20,
    example: "Bluetooth Headphones",
    note: "Optional. Pick from the dropdown; must be a sub-category of the chosen category.",
    dropdown: { list: "subcategories" },
  },
  {
    key: "brand_name",
    header: "brand_name",
    required: true,
    type: "string",
    width: 18,
    example: "Logitech",
    note: "Pick from the dropdown (sourced from the Brands sheet).",
    dropdown: { sheet: SHEET.BRANDS, column: 1 },
  },
  {
    key: "productType_name",
    header: "productType_name",
    required: true,
    type: "string",
    width: 18,
    example: "electronics",
    note: "Pick from the dropdown (sourced from the ProductTypes sheet).",
    dropdown: { sheet: SHEET.PRODUCT_TYPES, column: 1 },
  },
  {
    key: "additional_images",
    header: "additional_images",
    required: false,
    type: "urlList",
    width: 45,
    example:
      "https://res.cloudinary.com/demo/image/upload/v1/products/a.jpg | https://res.cloudinary.com/demo/image/upload/v1/products/b.jpg",
    note: "Optional. One or more full Cloudinary URLs separated by | (pipe).",
  },
  {
    key: "discount",
    header: "discount",
    required: false,
    type: "number",
    width: 10,
    example: 14,
    note: "Optional. Number >= 0 and <= price. Defaults to 0.",
  },
  {
    key: "unit",
    header: "unit",
    required: false,
    type: "string",
    width: 10,
    example: "1pcs",
    note: "Optional.",
  },
  // Multi-select tags: up to 5 tag columns, each a dropdown of the tag list.
  // The backend merges all non-empty tag_N values into the product's tags array.
  {
    key: "tag_1",
    header: "tag_1",
    required: false,
    type: "string",
    width: 18,
    example: "Best Seller",
    note: "Optional. Pick a tag. Use tag_2..tag_5 to add more tags to the same product.",
    dropdown: { list: "tags" },
  },
  {
    key: "tag_2",
    header: "tag_2",
    required: false,
    type: "string",
    width: 18,
    example: "New Arrival",
    note: "Optional second tag.",
    dropdown: { list: "tags" },
  },
  {
    key: "tag_3",
    header: "tag_3",
    required: false,
    type: "string",
    width: 18,
    example: "",
    note: "Optional third tag.",
    dropdown: { list: "tags" },
  },
  {
    key: "tag_4",
    header: "tag_4",
    required: false,
    type: "string",
    width: 18,
    example: "",
    note: "Optional fourth tag.",
    dropdown: { list: "tags" },
  },
  {
    key: "tag_5",
    header: "tag_5",
    required: false,
    type: "string",
    width: 18,
    example: "",
    note: "Optional fifth tag.",
    dropdown: { list: "tags" },
  },
  {
    key: "description",
    header: "description",
    required: false,
    type: "string",
    width: 40,
    example: "High fidelity wireless headphones with ANC.",
    note: "Optional.",
  },
  {
    key: "additionalInformation",
    header: "additionalInformation",
    required: false,
    type: "string",
    width: 40,
    example: "Weight: 250g; Warranty: 1 year",
    note: "Optional.",
  },
  {
    key: "offer_start_date",
    header: "offer_start_date",
    required: false,
    type: "date",
    width: 16,
    example: "2026-06-01",
    note: "Optional. YYYY-MM-DD. Required together with offer_end_date.",
  },
  {
    key: "offer_end_date",
    header: "offer_end_date",
    required: false,
    type: "date",
    width: 16,
    example: "2026-06-30",
    note: "Optional. YYYY-MM-DD. Must be after offer_start_date.",
  },
];

module.exports = {
  SHEET,
  STATUS_VALUES,
  CATEGORY_STATUS_VALUES,
  BRAND_STATUS_VALUES,
  COLOR_OPTIONS,
  TAG_OPTIONS,
  CATEGORY_COLUMNS,
  BRAND_COLUMNS,
  PRODUCT_TYPE_COLUMNS,
  PRODUCT_COLUMNS,
};
